FROM node:20.6.1-alpine3.18

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install app dependencies
COPY package.json ./
COPY package-lock.json ./
RUN npm install --immutable
# RUN npm install react-scripts@3.4.1 -g

# add app
COPY . ./

EXPOSE 8003
# start app
CMD ["npm", "run","dev"]