version: "3.1"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: budgeter-client_dev
    volumes:
      - .:/client/app
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./server/src:/app/src
      - ./server/certificates:/app/certificates
    expose:
      - '${SERVER_PORT}'