version: "3.1"
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: budgeter-client_dev
    volumes:
      - .:/app
    ports:
      - 3000:${CLIENT_PORT}
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev  # Assuming you have a Dockerfile in your ASP.NET project
    ports:
      - '80:${SERVER_PORT}'
