version: '3'
services:
  client:
    container_name: budgeter-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:${PORT}
    env_file:
      - .env
    volumes:
      - './ssl:/etc/nginx/cert'
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile  # Assuming you have a Dockerfile in your ASP.NET project
    ports:
      - '80:${SERVER_PORT}'
