version: "3.1"
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: budgeter-client_dev
    volumes:
      - .:/app
    ports:
      - 3000:${PORT}
    command: "npm run dev"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
