version: '3'
services:
  client:
    container_name: budgeter-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:3000
    env_file:
      - .env
    volumes:
      - './ssl:/etc/nginx/cert'
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./server/src:/app/src
      - ./server/certificates:/app/certificates
    expose:
      - '${SERVER_PORT}'
