version: '3'
services:
  client:
    container_name: budgeter-client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_PORT}:${CLIENT_PORT}
    env_file:
      - .env
    volumes:
      - './ssl:/etc/nginx/cert'
    
  server:
    build:
      context: ./server
      dockerfile: Dockerfile  # Assuming you have a Dockerfile in your ASP.NET project
    ports:
      - '${SERVER_PORT}:8080'
