# Use the appropriate .NET SDK image as a base
FROM mcr.microsoft.com/dotnet/sdk:7.0

# Set the working directory in the container
WORKDIR /app

# Copy the backend files to the working directory
COPY . .

# Restore dependencies
RUN dotnet restore

# Expose the port your ASP.NET app runs on
EXPOSE 8080

# Start the app in development mode
CMD ["dotnet", "watch", "run", "--urls", "http://0.0.0.0:8080"]